### PR TITLE
Wgdos only

### PR DESCRIPTION
**Pull request by pelson**
Replacement of #2 with only WGDOS packing support.

### CODE REVIEW

**Comment by lbdreyer** [comment]
Looking good. The only problem is that pep8 is complaining about some whitespace in lib/mo_pack/tests/test_wgdos.py

Other than that I am happy to merge.

**Comment by pelson** [comment]
Thanks @lbdreyer.

**Comment by rhattersley** [comment]
:tada: I believe this is @lbdreyer's first merge in a SciTools repo ... welcome aboard! :boat:

**Comment by pelson** [comment]
:+1: :tada:

**Pull request merged**
